fix: clean up code
leaphy-robotics/leaphy-webbased pull request #189
Opened 2024-03-23 21:07 UTC by koen1711

2024-03-23 21:07 UTC, koen1711 commented
On hold, just the beginning of the cleaning up

2024-03-24 10:13 UTC, koen1711 commented
Done with refactoring

2024-03-24 10:13 UTC, sverben requested changes

2024-03-24 10:13 UTC, sverben commented on src/app/domain/robot.type.ts
> +        public protocol: Partial<ProtocolInformation>,
Partial doesn't need to be used and removing can result in less if checks since the microcontroller param is already optional in the type

2024-03-24 10:13 UTC, sverben commented on src/app/domain/robot.type.ts
> +export const leaphyOriginalRobotType = new RobotType(
This shouldn't be in a type declaration file, renaming the file should be fine

2024-03-24 10:43 UTC, sverben approved these changes

2024-03-24 11:10 UTC, rmoesbergen approved these changes
ruimt lekker op

2024-03-24 11:10 UTC, merged